# This is a basic workflow to help you get started with Actions

name: Deploy dev to memery-server

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
      #   with:
      #     # the GCLOUD_SERVICE_ACCOUNT should be encoded in base64
      #     gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
      #     registry: asia.gcr.io
      #     project_id: memery
      #     image_name: memery-server-dev
        
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          ENV_FILE: ${{secrets.DEV_ENV_FILE}}
          APPLE_SIGN_IN_KEY: ${{secrets.APPLE_SIGN_IN_KEY}}
          FIREBASE_ADMIN: ${{secrets.FIREBASE_ADMIN}}
          GCP_KEY: ${{secrets.GCP_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          host: 35.221.128.211
          username: feveraly
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          envs: ENV_FILE, APPLE_SIGN_IN_KEY, FIREBASE_ADMIN, GCP_KEY
          script_stop: true
          script: |
            cd ~/memery-server
            echo -e "$ENV_FILE" > .env
            echo -e "$APPLE_SIGN_IN_KEY" > apple-sign-in-key.p8
            echo -e "$FIREBASE_ADMIN" > firebase-admin.json
            echo -e "$GCP_KEY" > gcp-key.json
            git pull https://feveral:$GITHUB_TOKEN@github.com/feveral/memery-server.git
            chmod u+x deploy-dev.sh
            ./deploy-dev.sh
